### ISSUE TITLE
Misalignment in admonitions when using the ones provided by Admonition Panels plugin

### ISSUE THREAD

**Issue by riccardotrz** [henices/logseq-flow-nord#1]
Hi I'm using Logseq Flow Nord theme with admonitions provided by the Admonition Panels plugin ([https://github.com/nmartin84/admonition-panels](https://github.com/nmartin84/admonition-panels))

The visual rendering of such admonitions is somehow broken (see the misalignment between upper and lower part of the admonition)

![image](https://github.com/henices/logseq-flow-nord/assets/13435366/27c5b5c1-5cf8-4cd4-87a1-2c10ad464c61)

No problems when using the regular admonitions provided by Logseq itself

```
#+BEGIN_TIP
Tutorial Videos: [Tutorial Videos | Cypress Documentation](https://docs.cypress.io/examples/examples/tutorials)
#+END_TIP
```
results in 

![image](https://github.com/henices/logseq-flow-nord/assets/13435366/185fc20c-8588-4c39-be73-4c2f1a286ec1)

My environment:

- Logseq 0.9.8
- Admonition Panels plugin 0.1.1
- Logseq Flow Nord  0.1.2

**Comment by henices** [comment]
Sorry, I can't access https://github.com/nmartin84/admonition-panels now :(

**Comment by riccardotrz** [comment]
Me too. I wonder whether that plugin is still "alive" (i.e. "supported")
Nevertheless the plugin is available in the Logseq Plugin Marketplace. Thus anyone can install it and encounter the issue described above, right?

If that plugin is "dead", I guess it should be removed from the list of the ones that can be installed but I've no idea who to talk to in Logseq management team to handle this situation

**Comment by henices** [comment]
> Me too. I wonder whether that plugin is still "alive" (i.e. "supported") Nevertheless the plugin is available in the Logseq Plugin Marketplace. Thus anyone can install it and encounter the issue described above, right?
> 
> If that plugin is "dead", I guess it should be removed from the list of the ones that can be installed but I've no idea who to talk to in Logseq management team to handle this situation

Could you please tell the plugin name in the Logseq Plugin Marketplace.

**Comment by riccardotrz** [comment]
Adminition Panels (as in the title of this issue)

**Comment by henices** [comment]
> Adminition Panels (as in the title of this issue)

Can you find in  https://github.com/logseq/marketplace/tree/master/packages

**Comment by riccardotrz** [comment]
Cannot find the Admonition Panels (logseq-admonition-panels) in the link you provided
I had it installed in my Logseq since months ago but now, after an uninstallation, I cannot re-add it from the Marketplace
Another indication of a "dead" plugin, presumably

By tyhe way, I simply got rid of the custom admonitions, replacing them with the standard ones provided by Logseq itself.
Do you think we can simply close this issue?

**Comment by henices** [comment]
> Cannot find the Admonition Panels (logseq-admonition-panels) in the link you provided I had it installed in my Logseq since months ago but now, after an uninstallation, I cannot re-add it from the Marketplace Another indication of a "dead" plugin, presumably
> 
> By tyhe way, I simply got rid of the custom admonitions, replacing them with the standard ones provided by Logseq itself. Do you think we can simply close this issue?

Sure, I think we can close this issue.  Have a good day.
