### ISSUE TITLE
How to modify CSS so that the numbers in the sequence table are at the same height as the first row.

### ISSUE THREAD

**Issue by Dustin-Hayes-Hong** [henices/logseq-flow-nord#17]
I really like Nord's color scheme, but the numbers in the ordered list are highly centered.
![image](https://github.com/henices/logseq-flow-nord/assets/78560143/178641e7-e11b-48b3-a16d-2f789a88f877)
I prefer standard ordered lists, how can I modify CSS?
![image](https://github.com/henices/logseq-flow-nord/assets/78560143/97a15bd1-9cf8-42aa-9f0c-0de1a84584d3)

**Comment by henices** [comment]
Thanks for reporting this issue. I 'll look into it.

**Comment by henices** [comment]
Can you provide more details to reproduce.  I test the Numbered List, but I can't reproduce it.

![image](https://github.com/henices/logseq-flow-nord/assets/929715/5f325d83-0870-4f5f-86fa-07ffa5046b10)

**Comment by Dustin-Hayes-Hong** [comment]
> Can you provide more details to reproduce. I test the Numbered List, but I can't reproduce it.
> 
> ![image](https://private-user-images.githubusercontent.com/929715/294805577-5f325d83-0870-4f5f-86fa-07ffa5046b10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODQzNjYsIm5iZiI6MTcwNDY4NDA2NiwicGF0aCI6Ii85Mjk3MTUvMjk0ODA1NTc3LTVmMzI1ZDgzLTA4NzAtNGY1Zi04NmZhLTA3ZmZhNTA0NmIxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQwMzIxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWEwYzI1ZjRjNzQ4ZmJlZWZiY2QxYjFmYmFhYzBjMjEzMjY3NWI4MWJmZWRiNDA4MzMyNDEyYmFlOWJkYWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.59uZ0c_UZ4wWIuYYIw-eZw8GZCR0Upi3jstxis4gx48) ![image](https://private-user-images.githubusercontent.com/929715/294805947-ba85a833-7c29-4ba6-9932-a1d8c832d542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODQzNjYsIm5iZiI6MTcwNDY4NDA2NiwicGF0aCI6Ii85Mjk3MTUvMjk0ODA1OTQ3LWJhODVhODMzLTdjMjktNGJhNi05OTMyLWExZDhjODMyZDU0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQwMzIxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzQwYTRkZWI3Y2M3Yjk3YTMxZTBmYTQzMjEwZjA2YjljODQ0YmRjYmQ4MmNlZGNmYzAxN2Y4YWMzYWRkOGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sHglNwdy13dzxxrFNPADhUggHXSGpkddPxTgKIjN5Po)

I choose "Flow Nord Theme-Nord".

**Comment by henices** [comment]
![image](https://github.com/henices/logseq-flow-nord/assets/929715/e446aa6f-0d26-464a-a6fe-265a2cd56551)

**Comment by Dustin-Hayes-Hong** [comment]
> ![image](https://private-user-images.githubusercontent.com/929715/294808027-e446aa6f-0d26-464a-a6fe-265a2cd56551.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MzMxMDUsIm5iZiI6MTcwNDczMjgwNSwicGF0aCI6Ii85Mjk3MTUvMjk0ODA4MDI3LWU0NDZhYTZmLTBkMjYtNDY0YS1hNmZlLTI2NWEyY2Q1NjU1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNjUzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDkwNTYzYWY3ODNhMjI1ZjRiOGVhNDM5N2Q3NGJmNGVkOGQxODM2ZDYzZGZiMTc0NWZmMzkzYTUzN2IyNzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3rrqDoCATkyC1qMWZ9ZWuPaTKM-20ehdS3oET-dw5Uo) ![image](https://private-user-images.githubusercontent.com/929715/294818776-4beae408-3f70-464c-a309-43b0f5e3ba74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MzMxMDUsIm5iZiI6MTcwNDczMjgwNSwicGF0aCI6Ii85Mjk3MTUvMjk0ODE4Nzc2LTRiZWFlNDA4LTNmNzAtNDY0Yy1hMzA5LTQzYjBmNWUzYmE3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNjUzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGE2ZDA1ODQ0YTE4MWIzNDQ5ZDA3NTcxZjEyMmM4ZTYxMGRmNjM2M2IzMTdjMmFjMmI1MTM5MTRkYmQ0ZjAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BbmDgR11K2HwA1SGCnj1IwfNB1ha4nkJUfkfXpdYlkc)

It's really a strange thing, I can't give you more feedback, I will ignore this issue and continue to use it.
