### ISSUE TITLE
API issue using loqseq on 2 different computers

### ISSUE THREAD

**Issue by LoomingMountain** [henices/logseq-flow-nord#18]
Hello,

I'm using loqseq on two different computers: work and personal. When I try to download the flow nord theme, which I really like, on my 2nd computer (work) I get an error message and the theme doesn't really work for me.

I get this response:
82B4:1D7B6C:D80247:DA1D4F:659BD5BF.\",\"documentation_url\":\"https://docs.github.com/rest/overview/rate-limits-for-the-rest-api\"}"]

There seems to be an API issue, using the theme on two different computers.

Is there something I can do to fix this?

All the best,
J.

**Comment by henices** [comment]
Thanks for reporting this issue.  It seems the Github api which Logseq requested is exceed the limit.

Try to download Logseq Flow Nord Theme tomorrow morning.  If you still get the api request error, report an issue in https://github.com/logseq/logseq/issues

**Comment by henices** [comment]
CC @xyhp915
