### ISSUE TITLE
Safe to update to 0.10.4?

### ISSUE THREAD

**Issue by kerim** [henices/logseq-flow-nord#19]
I saw that the new nightly build breaks some existing themes. Is it safe to update to 0.10.4 if I use the Flow Nord theme?

**Comment by henices** [comment]
Yes, the latest version of Logseq Flow Nord Theme is ready for Logseq v0.10.4.

Please upgrade Logseq Flow Nord Theme is thel market place and restart Logseq.  I hope you can enjoy with it !   😄
