### ISSUE TITLE
Ligatures not working with any of the flow-nord variants

### ISSUE THREAD

**Issue by arigit** [henices/logseq-flow-nord#26]
Hi, first, thank your for this theme. I find your Flow Nord Theme - One dark pro theme the best nord-based theme for logseq and wanted to use it. One problem though, I couldn't solve.

I use fonts with support of ligatures. Inter is my default font (but the problem can be replicated with any font that supports ligatures.

This this simple custom css to change the font:

```@import url("https://fonts.googleapis.com/css2?family=Fira+Code&display=swap"); */

:root {
 --ls-font-family: "Inter", sans-serif !important;
}
```

In bonofix or in the logseq default theme, if in a block I writte -> --> ---> ----> it renders like this:

![image](https://github.com/user-attachments/assets/8eb9d962-e482-4e8b-9975-1ec11199e9d9)

In the default theme: 
![image](https://github.com/user-attachments/assets/968071d0-2483-4501-8bef-c4c1ff403134)

If I change the theme to the any of the Flow Nord themes, I get, for the exact same block:

![image](https://github.com/user-attachments/assets/804e44e5-33e6-44f1-969d-2e3c618f44b9)

i.e., ligatures do not render at all with your theme for some reason. I experimented with various custom.css hacks, I couldn't find a way to get ligatures to work. This happens with any font that supports ligatures, I tested various.

Curiously, insdie code-mirror blocks, no problem, ligatures work if they are enabled like so:

```
blockquote .CodeMirror pre.CodeMirror-line {
    font-family: "Inter", "Fira Code", monospace !important;
    font-variant-ligatures: normal;
    font-size: 110%;
}
```

But - I want ligatures to work on normal text blocks too, it's the most important use case for me.

Any suggestion on how to get ligatures to work with the nord theme? any hack on custom.css that fixes this would be wonderful.

**Comment by arigit** [comment]
I figured a workaround to enable ligatures in this theme, by looking at other themes where ligatures work out of the box. I noticed that most themes have a "font-feature-settings" value almost for every selector, and this theme lacks it.

In short, this fixed my problem:
In custom.css:

```
:root {
  --ls-font-family: "Inter", sans-serif !important;
  --ml-feature-settings: "ss01" 1, "ss02" 1, "ss03" 1, "ss06" 1, "ss10" 1,
    "ss11" 1, "zero", "onum", "liga" 1, "calt" 1;
  --ls-font-feature-settings: var(--ml-feature-settings);
  --cl-font-family: var(--ls-font-family);
}

html, body {
  /* ligatures in normal blocks work out of the box in the default and bonofix
      themes, no need of the below; however they fail in Flow Nord, issue opened  */
  font-variant-ligatures: normal !important;
  font-feature-settings: var(--ls-font-feature-settings);
}
```

**Comment by henices** [comment]
Sorry for the late reply,  I'll look into it.

**Comment by henices** [comment]
Logseq Flow Nord Theme is now use  ` font-feature-settings: "zero", "liga" 1, "calt" 1;` by default.

Please Put the following code in `custom.css` :

```css
:root {
  --cl-font-family: "Inter", sans-serif;
  --cl-font-feature-settings: "ss01" 1, "ss02" 1, "ss03" 1, "ss06" 1, "ss10" 1, "ss11" 1, "zero", "onum", "liga" 1, "calt" 1;
}
```

Thanks for your contribution.
