### ISSUE TITLE
Mouse cursor doesn't change to input mode while using column function

### ISSUE THREAD

**Issue by oriofdarkforest** [henices/logseq-flow-nord#8]
您好，我非常喜欢您做的主题！现在也在使用它。但在使用时发现了在使用多列时光标会不显示的问题。
不开启多列时，无论鼠标离小圆点多远，只要当前行存在，鼠标指针就会变为输入的指针。但是开启多列后，有时鼠标指针不发生变化。
我在使用预设的模板，鼠标指针不变化会为输入带来一些困难。希望您可以优化它。
再次感谢您制作的主题！超赞！

Hello, I really like the theme you've created! I'm currently using it as well. However, while using it, I've encountered an issue with the cursor not showing when using multiple columns.
When not using multiple columns, regardless of how far the mouse is from the bullet point, as long as the current line exists, the mouse cursor changes to the input pointer. But when using multiple columns, sometimes the mouse cursor doesn't change.
I'm using the template function, and the cursor issue brings some difficulties to the input. I hope you can optimize it.
Thanks again for the theme you've made! It's fantastic!

**Comment by oriofdarkforest** [comment]
here it is. hope it helps
https://github.com/henices/logseq-flow-nord/assets/72719841/ca675709-2d48-4922-ba46-94bf2bf38fa9

**Comment by henices** [comment]
New version of Logseq Flow Nord theme is released. You can upgrade theme from the Logseq marketplace.

Thanks a lot.

**Comment by oriofdarkforest** [comment]
Fantastic! Thank you for the optimization!
