### ISSUE TITLE
When the title is too long, the second column will not align correctly

### ISSUE THREAD

**Issue by oriofdarkforest** [henices/logseq-flow-nord#9]
Found a small issue. When there's nested block in first column and the title of first column takes more than 1 line, the second column will align to the nested block in first column.
![image](https://github.com/henices/logseq-flow-nord/assets/72719841/f194d885-1a97-4477-931b-d3e1266f5a3f)

Love this theme and the parallel!

**Comment by henices** [comment]
good catch !  Maybe I should redesgin the layout.

**Comment by oriofdarkforest** [comment]
![image](https://github.com/henices/logseq-flow-nord/assets/72719841/42120830-b0e7-4ddf-91cc-2dffc0148c1f)
Same thing happened to the admonition.

And parallel not works for Example. You can see the length of colored block is not changed with parallel-2 tag.
![image](https://github.com/henices/logseq-flow-nord/assets/72719841/7597aa44-3fc5-4d9e-9241-d2f8f02f661b)

Many thanks!
